// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace YoutubeDevExpressMVC.Web.Models.Db
{

    // CustomerCustomerDemo
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.4.0")]
    public class CustomerCustomerDemo
    {
        public int CustomerId { get; set; } // CustomerId (Primary key)
        public int CustomerDemographicId { get; set; } // CustomerDemographicId (Primary key)

        // Foreign keys

        /// <summary>
        /// Parent Customer pointed by [CustomerCustomerDemo].([CustomerId]) (FK_CustomerCustomerDemo_Customer)
        /// </summary>
        public virtual Customer Customer { get; set; } // FK_CustomerCustomerDemo_Customer

        /// <summary>
        /// Parent CustomerDemographic pointed by [CustomerCustomerDemo].([CustomerDemographicId]) (FK_CustomerCustomerDemo_CustomerDemographic)
        /// </summary>
        public virtual CustomerDemographic CustomerDemographic { get; set; } // FK_CustomerCustomerDemo_CustomerDemographic
    }

}
// </auto-generated>
