//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YoutubeDevExpressMVC.Web.Models.Db
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NorthwindRevEntities : DbContext
    {
        public NorthwindRevEntities()
            : base("name=NorthwindRevEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<CustomerDemographic> CustomerDemographics { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<OrderDetail> OrderDetails { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Region> Regions { get; set; }
        public virtual DbSet<Shipper> Shippers { get; set; }
        public virtual DbSet<Supplier> Suppliers { get; set; }
        public virtual DbSet<Territory> Territories { get; set; }
        public virtual DbSet<ViewAlphabeticalListOfProduct> ViewAlphabeticalListOfProducts { get; set; }
        public virtual DbSet<ViewCategorySalesFor1997> ViewCategorySalesFor1997 { get; set; }
        public virtual DbSet<ViewCurrentProductList> ViewCurrentProductLists { get; set; }
        public virtual DbSet<ViewCustomerAndSuppliersByCity> ViewCustomerAndSuppliersByCities { get; set; }
        public virtual DbSet<ViewInvoice> ViewInvoices { get; set; }
        public virtual DbSet<ViewOrderDetailsExtended> ViewOrderDetailsExtendeds { get; set; }
        public virtual DbSet<ViewOrdersQry> ViewOrdersQries { get; set; }
        public virtual DbSet<ViewOrderSubtotal> ViewOrderSubtotals { get; set; }
        public virtual DbSet<ViewProductsAboveAveragePrice> ViewProductsAboveAveragePrices { get; set; }
        public virtual DbSet<ViewProductSalesFfor1997> ViewProductSalesFfor1997 { get; set; }
        public virtual DbSet<ViewProductsByCategory> ViewProductsByCategories { get; set; }
        public virtual DbSet<ViewSalesByCategory> ViewSalesByCategories { get; set; }
        public virtual DbSet<ViewSalesTotalsByAmount> ViewSalesTotalsByAmounts { get; set; }
        public virtual DbSet<ViewSummaryOfSalesByQuarter> ViewSummaryOfSalesByQuarters { get; set; }
        public virtual DbSet<ViewSummaryOfSalesByYear> ViewSummaryOfSalesByYears { get; set; }
    }
}
