//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YoutubeDevExpressMVC.Web.Models.DbGenel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeFile
    {
        public int Id { get; set; }
        public int EmployeeId { get; set; }
        public string FileUrl { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
