//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YoutubeDevExpressMVC.Web.Models.DbRandevu
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NorthwindRevEntitiesRandevu : DbContext
    {
        public NorthwindRevEntitiesRandevu()
            : base("name=NorthwindRevEntitiesRandevu")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Hasta> Hastas { get; set; }
        public virtual DbSet<Randevu> Randevus { get; set; }
    }
}
