// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace YoutubeDevExpressMVC.Web.Models.Db
{

    // CustomerDemographic
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.4.0")]
    public class CustomerDemographic : IEntity
    {
        public int Id { get; set; } // Id (Primary key)
        public string CustomerDesc { get; set; } // CustomerDesc (length: 1073741823)
        public string Code { get; set; } // Code (length: 10)

        // Reverse navigation

        /// <summary>
        /// Child CustomerCustomerDemoes where [CustomerCustomerDemo].[CustomerDemographicId] point to this entity (FK_CustomerCustomerDemo_CustomerDemographic)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<CustomerCustomerDemo> CustomerCustomerDemoes { get; set; } // CustomerCustomerDemo.FK_CustomerCustomerDemo_CustomerDemographic

        public CustomerDemographic()
        {
            CustomerCustomerDemoes = new System.Collections.Generic.List<CustomerCustomerDemo>();
        }
    }

}
// </auto-generated>
