// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace YoutubeDevExpressMVC.Web.Models.Db
{

    // CustomerCustomerDemo
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.4.0")]
    public class CustomerCustomerDemoConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<CustomerCustomerDemo>
    {
        public CustomerCustomerDemoConfiguration()
            : this("dbo")
        {
        }

        public CustomerCustomerDemoConfiguration(string schema)
        {
            ToTable("CustomerCustomerDemo", schema);
            HasKey(x => new { x.CustomerId, x.CustomerDemographicId });

            Property(x => x.CustomerId).HasColumnName(@"CustomerId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.CustomerDemographicId).HasColumnName(@"CustomerDemographicId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);

            // Foreign keys
            HasRequired(a => a.Customer).WithMany(b => b.CustomerCustomerDemoes).HasForeignKey(c => c.CustomerId).WillCascadeOnDelete(false); // FK_CustomerCustomerDemo_Customer
            HasRequired(a => a.CustomerDemographic).WithMany(b => b.CustomerCustomerDemoes).HasForeignKey(c => c.CustomerDemographicId).WillCascadeOnDelete(false); // FK_CustomerCustomerDemo_CustomerDemographic
        }
    }

}
// </auto-generated>
